manifest = "67850a8b34845f57e65186dbe516e99fa14378b55d20b1bd2950acd6a92d7749"

[[dependency]]
package = "github.com/buckaroo-pm/host-core-foundation"
target = "//:core-foundation"

[lock."github.com/buckaroo-pm/host-core-foundation"]
versions = [ "branch=master" ]
revision = "fd7081ffe1244afb86c41c2d41d3603f851feae8"
