manifest = "67850a8b34845f57e65186dbe516e99fa14378b55d20b1bd2950acd6a92d7749"

[[dependency]]
package = "github.com/buckaroo-pm/host-core-foundation"
target = "//:core-foundation"

[[lock]]
name = "github.com/buckaroo-pm/host-core-foundation"
revision = "5026cb425ebbf790c3d1360c041a5dde52a60ab8"
